init_x: 0  # initial x-pos 
init_y: 0  # initial y-pos
init_z: 20  # initial z-pos
init_psi: 0  # initial heading

max_omega: 100.0  # drone max angular velocity
max_zvel: 5  # drone max vertical velocity

vehicle_l: 3  # vehicle list for visualization
vehicle_num: $(arg vehicle_num)

hvel: 30  # vehicle x-y velocity
vvel: 2  # vehicle z-velocity

# number of random targets & obstalces
# -1 if providing custom list of targets
n_rand_targets: 10
n_rand_obst: 200 

del_t: .02  # timestep between sim updates

waypt_threshold: 3.0

min_formation_dist: 50
max_formation_dist: 100

K_p: 10  # PID angular proportionality constant
K_p_z: 0.01  # PID z-axis proportionality constant

# targets:
#   - {id: 1, x: 900,  y: 500,  heading: 1.5, linear_speed: 0., angular_speed: 0., linear_speed_std: 0.2, angular_speed_std: 0.01}
#   - {id: 2, x: 700,  y: -500, heading: 1.5, linear_speed: 0., angular_speed: 0., linear_speed_std: 0.2, angular_speed_std: 0.01}
#   - {id: 3, x: 1100, y: -150, heading: 1.5, linear_speed: 0., angular_speed: 0., linear_speed_std: 0.2, angular_speed_std: 0.01}
#   - {id: 4, x: 1200, y: 250,  heading: 1.5, linear_speed: 0., angular_speed: 0., linear_speed_std: 0.2, angular_speed_std: 0.01}
#   - {id: 5, x: 1600, y: 0,    heading: 1.5, linear_speed: 0., angular_speed: 0., linear_speed_std: 0.2, angular_speed_std: 0.01}
#   - {id: 6, x: 800,  y: -250, heading: 1.5, linear_speed: 0., angular_speed: 0., linear_speed_std: 0.2, angular_speed_std: 0.01}

# obstacles:
#   - {id: 1, x: 800,  y: 300,  width: 50., length: 50., height: 200., speed: 0.0, hold_heading_time: 4.2}
#   - {id: 2, x: 600,  y: 400,  width: 50., length: 50., height: 200., speed: 0.0, hold_heading_time: 4.0}
#   - {id: 3, x: 900,  y: 0,    width: 50., length: 50., height: 200., speed: 0.0, hold_heading_time: 6.0}
#   - {id: 4, x: 500,  y: 700,  width: 50., length: 50., height: 200., speed: 0.0, hold_heading_time: 4.0}
#   - {id: 5, x: 1200, y: -400, width: 50., length: 50., height: 200., speed: 0.0, hold_heading_time: 3.0}
#   - {id: 6, x: 400,  y: 100,  width: 50., length: 50., height: 200., speed: 0.0, hold_heading_time: 4.0}
#   - {id: 7, x: -200, y: -200, width: 50., length: 50., height: 200., speed: 0.0, hold_heading_time: 5.0}
#   - {id: 8, x: 1300, y: -800, width: 50., length: 50., height: 200., speed: 0.0, hold_heading_time: 4.0}

sensor_a: 1
sensor_b: 1
sensor_d: 1
sensor_g: 1
sensor_h: 1

sensor_focal_length: 20
sensor_width: 10
sensor_height: 10
sensor_pitch: 1.13  # 0.349
sensor_yaw: 0
